In [2]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold,train_test_split
from sklearn.preprocessing import LabelEncoder

In [3]:
train_data=pd.read_csv(r"C:\Users\hp\AppData\Roaming\Microsoft\Windows\Start Menu\train.csv")
train_data.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [4]:
test_data=pd.read_csv(r"C:\Users\hp\AppData\Roaming\Microsoft\Windows\Start Menu\test.csv")
test_data.head()

,ID,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,1,az,v,n,f,d,t,a,w,0,...,0,0,0,1,0,0,0,0,0,0
1,2,t,b,ai,a,d,b,g,y,0,...,0,0,1,0,0,0,0,0,0,0
2,3,az,v,as,f,d,a,j,j,0,...,0,0,0,1,0,0,0,0,0,0
3,4,az,l,n,f,d,z,l,n,0,...,0,0,0,1,0,0,0,0,0,0
4,5,w,s,as,c,d,y,i,m,0,...,1,0,0,0,0,0,0,0,0,0

In [6]:
train_data.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

AS WE CAN SEE ABOVE THE TRAIN AND TEST DATA IS BALANCED DATA MEAN ALMOST EQUAL TO 50%

In [7]:
for i in train_data.columns:
    data_type=train_data[i].dtype
    if data_type=='object':
        print(i)

X0
X1
X2
X3
X4
X5
X6
X8

Now we need to remove the cell which have data type 'object'

NOW WE WILL CHECK FOR MISSING VALUES

In [8]:
train_data.isnull().sum()

ID      0
y       0
X0      0
X1      0
X2      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 378, dtype: int64

In [9]:
#as above we can not scroll down and see all values we can use other code
train_data.isnull().sum().any()

False

In [ ]:
#there are no missing values

In [11]:
train_data.describe(include='object')

          X0    X1    X2    X3    X4    X5    X6    X8
count   4209  4209  4209  4209  4209  4209  4209  4209
unique    47    27    44     7     4    29    12    25
top        z    aa    as     c     d     w     g     j
freq     360   833  1659  1942  4205   231  1042   277

In [14]:
le=LabelEncoder()
train_data['x0']=le.fit_transform(train_data.X0)
train_data['x1']=le.fit_transform(train_data.X1)
train_data['x2']=le.fit_transform(train_data.X2)
train_data['x3']=le.fit_transform(train_data.X3)
train_data['x4']=le.fit_transform(train_data.X4)
train_data['x5']=le.fit_transform(train_data.X5)
train_data['x6']=le.fit_transform(train_data.X6)
train_data['x8']=le.fit_transform(train_data.X8)

In [18]:
train_data.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X384,X385,x0,x1,x2,x3,x4,x5,x6,x8
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,32,23,17,0,3,24,9,14
1,6,88.53,k,t,av,e,d,y,l,o,...,0,0,32,21,19,4,3,28,11,14
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,20,24,34,2,3,27,9,23
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,20,21,34,5,3,27,11,4
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,20,23,34,5,3,12,3,13

In [21]:
x=train_data.drop(columns={'ID','y','X0','X1','X2','X3','X4','X5','X6','X8'})

In [22]:
Y=train_data.y

In [23]:
Y

0       130.81
1        88.53
2        76.26
3        80.62
4        78.02
         ...
4204    107.39
4205    108.77
4206    109.22
4207     87.48
4208    110.85
Name: y, Length: 4209, dtype: float64

In [24]:
x

,X10,X11,X12,X13,X14,X15,X16,X17,X18,X19,...,X384,X385,x0,x1,x2,x3,x4,x5,x6,x8
0,0,0,0,1,0,0,0,0,1,0,...,0,0,32,23,17,0,3,24,9,14
1,0,0,0,0,0,0,0,0,1,0,...,0,0,32,21,19,4,3,28,11,14
2,0,0,0,0,0,0,0,1,0,0,...,0,0,20,24,34,2,3,27,9,23
3,0,0,0,0,0,0,0,0,0,0,...,0,0,20,21,34,5,3,27,11,4
4,0,0,0,0,0,0,0,0,0,0,...,0,0,20,23,34,5,3,12,3,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,0,0,0,0,1,0,0,0,0,0,...,0,0,8,20,16,2,3,0,3,16
4205,0,0,0,0,0,0,0,0,0,0,...,0,0,31,16,40,3,3,0,7,7
4206,0,0,1,1,0,0,0,0,0,0,...,0,0,8,23,38,0,3,0,6,4
4207,0,0,0,0,1,0,0,0,0,0,...,0,0,9,19,25,5,3,0,11,20
4208,0,0,0,0,0,0,0,0,0,0,...,0,0,46,19,3,2,3,0,6,22

In [35]:
k=PCA(n_components=6)
k.fit(x,Y)

PCA(n_components=6)

In [36]:
train_data_feture=k.fit_transform(x)
train_data_feture.shape

(4209, 6)

NOW DATA ANALYSIS PART IS DONE, AND THE DATA IS READY FOR PREDICTION MODEL